### PR TITLE
Numerous changes.

### PR DESCRIPTION
**Pull request by danslo**
I am not sure if you are interested in merging this, but it doesn't hurt to try :-)

Following things implemented:
- Switched to composer based deployments.
- Use [LibraryRewrite](https://github.com/danslo/LibraryRewrite/) module instead of copying entire lib classes (which was from Enterprise edition, no less).
- Load [Vinai's PSR-0 autoloader](https://github.com/magento-hackathon/Magento-PSR-0-Autoloader/) and use it to load the official [Amazon PHP SDK](https://github.com/aws/aws-sdk-php).
- Implement the Amazon PHP SDK by implementing the interface of the original connector.
- Fix the WYSIWYG bug by lazy-loading the connector.
- Added license headers all over the place.

Once (if!) this gets merged, you only need to do two things:
- [x] Create a new tag starting at 1.0.0.
- [x] Update the vcs repository in composer.json to point at this repository instead.

The reason why a new tag is important, is so that users with `~0.0.1` aren't broken by this merge. It's also critical for picking up the composer.json in the magento composer installer.

### CODE REVIEW

**Comment by danslo** [comment]
@Zyava Thanks for merging! Please don't forget the 2 checkboxes above, they are pretty important.

**Comment by Zyava** [comment]
Thank you for great pull request! Unfortunately, we do not use this module in any our projects anymore so I can't test your changes. However, two big projects are coming so maybe we will start using it again.

**Comment by danslo** [comment]
Is there a particular reason for not using it anymore? Something better for S3 that I'm missing? :)

**Comment by Zyava** [comment]
No, just client decided to switch from magento to Adobe CQ5

**Pull request merged**
